-- migrations/0127_graph_edges.sql
--
-- Graph memory, Phase 1 (docs/private/graph-memory-spec-2026-08-28.md). One table: a DERIVED,
-- DISPOSABLE projection over D1's existing relationships. Nothing here is a source of truth --
-- every row can be deleted and regenerated by src/graph/rebuild.ts::rebuildGraph. Append-only
-- source tables (relational_deltas, companion_journal, inter_companion_notes, handover_packets,
-- companion_conclusions, companion_tensions) are never written to by the rebuild; this table is
-- the only thing it ever mutates.
--
-- IDENTITY. UNIQUE(src_table, src_id, dst_table, dst_id, edge_type) is the real key -- `id` exists
-- only because every other table in this schema carries one (default matches
-- companion_conclusions: lower(hex(randomblob(16)))), and D1/Hearth tooling that assumes a PK
-- column keeps working. Rebuild uses INSERT OR IGNORE keyed on the UNIQUE constraint, so re-running
-- it twice against unchanged source data produces the exact same row set (deterministic, idempotent).
--
-- created_at CARRIES THE SOURCE RELATIONSHIP'S BIRTH TIME, not datetime('now') -- an edge rebuilt
-- today from a note sent three months ago is dated three months ago. See rebuild.ts for exactly
-- which source column feeds each edge_type.
--
-- NO ranking/heat/read-tracking columns. This is 0112's lesson generalized: an edge may exist or
-- not; nothing about surfacing it may write back onto it. Heat lives on the SOURCE rows (companion_
-- journal.heat, companion_conclusions.heat, mig 0105) if a consumer wants a warmth signal --
-- graph_edges is structure, not salience.
--
-- provenance: 'mechanical' for every row this phase can produce (a deterministic derivation from
-- an existing column). 'mechanical:broadcast' marks the one case where one source row fans out to
-- several edges (an inter_companion_notes broadcast, to_id IS NULL). 'mechanical:status=<value>'
-- (companion_tensions) encodes the current status inline since there is no event history to derive
-- a real timestamped transition from. Future phases may add 'proposed' (companion-asserted, unconfirmed)
-- and 'ratified' (companion-confirmed) lanes -- do not build them yet; this migration reserves the
-- column's shape, not its values.
--
-- writer: the companion/system that authored the underlying relationship -- a note's from_id, a
-- conclusion's companion_id, 'system' for structural links nobody authored (session -> handover).
--
-- sibling_notes (mig 0126) is a structurally sealed companion-only lane (src/__tests__/sibling-
-- seal.test.ts). It MUST NEVER appear in this table, as src_table or dst_table, in this phase or any
-- future one -- surfacing it here would leak a sealed relationship onto a derived table nothing
-- forbids Raziel-facing code from reading.

CREATE TABLE IF NOT EXISTS graph_edges (
  id         TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  src_table  TEXT NOT NULL,
  src_id     TEXT NOT NULL,
  dst_table  TEXT NOT NULL,
  dst_id     TEXT NOT NULL,
  edge_type  TEXT NOT NULL,
  writer     TEXT NOT NULL,
  provenance TEXT NOT NULL DEFAULT 'mechanical',
  created_at TEXT NOT NULL,
  UNIQUE (src_table, src_id, dst_table, dst_id, edge_type)
);

-- Rebuild's DELETE FROM graph_edges WHERE provenance LIKE 'mechanical%' -- this index makes that
-- scan cheap regardless of table size.
CREATE INDEX IF NOT EXISTS idx_graph_edges_provenance ON graph_edges(provenance);

-- The two directions a graph read actually walks: "what points at this node" and "what does this
-- node point at". edge_type is appended to each so a caller can filter without a second pass.
CREATE INDEX IF NOT EXISTS idx_graph_edges_src ON graph_edges(src_table, src_id, edge_type);
CREATE INDEX IF NOT EXISTS idx_graph_edges_dst ON graph_edges(dst_table, dst_id, edge_type);
